/**
 * Curated dictionary of common grocery ingredients for the pantry autocomplete.
 * Lowercased to match recipe ingredient naming (matching is case-insensitive and
 * substring-based, so "chicken" matches "chicken thighs"). Merged at runtime with
 * every ingredient used across the recipe library.
 */
export const INGREDIENT_DICTIONARY: string[] = [
  // Proteins
  'chicken breasts',
  'chicken thighs',
  'ground beef',
  'ground turkey',
  'steak',
  'flank steak',
  'pork chops',
  'pork shoulder',
  'bacon',
  'sausage',
  'salmon',
  'shrimp',
  'tilapia',
  'tuna',
  'tofu',
  'eggs',
  'black beans',
  'kidney beans',
  'chickpeas',
  'lentils',
  // Produce
  'onion',
  'red onion',
  'green onions',
  'garlic',
  'ginger',
  'carrots',
  'celery',
  'potatoes',
  'sweet potatoes',
  'baby potatoes',
  'bell pepper',
  'jalapeno',
  'broccoli',
  'cauliflower',
  'zucchini',
  'eggplant',
  'mushrooms',
  'spinach',
  'kale',
  'lettuce',
  'cabbage',
  'cucumber',
  'tomatoes',
  'cherry tomatoes',
  'avocado',
  'corn',
  'green beans',
  'snap peas',
  'asparagus',
  'lemon',
  'lime',
  'cilantro',
  'parsley',
  'basil',
  'thai basil',
  'mint',
  'shallot',
  // Dairy & eggs
  'butter',
  'milk',
  'heavy cream',
  'sour cream',
  'greek yogurt',
  'cream cheese',
  'cheddar cheese',
  'parmesan',
  'mozzarella',
  'feta cheese',
  // Grains & dry goods
  'rice',
  'basmati rice',
  'jasmine rice',
  'brown rice',
  'pasta',
  'penne pasta',
  'spaghetti',
  'orzo',
  'couscous',
  'quinoa',
  'flour',
  'bread',
  'tortillas',
  'corn tortillas',
  'burger buns',
  'pita bread',
  'panko breadcrumbs',
  'oats',
  // Cans & jars
  'crushed tomatoes',
  'tomato paste',
  'coconut milk',
  'chicken broth',
  'beef broth',
  'vegetable broth',
  'salsa',
  'bbq sauce',
  'soy sauce',
  'teriyaki sauce',
  'hoisin sauce',
  'fish sauce',
  'curry paste',
  'red curry paste',
  'peanut butter',
  'hummus',
  'tahini',
  'olives',
  // Oils, vinegars, sweeteners
  'olive oil',
  'vegetable oil',
  'sesame oil',
  'balsamic vinegar',
  'rice vinegar',
  'honey',
  'maple syrup',
  'brown sugar',
  'sugar',
  // Spices & seasonings
  'salt',
  'black pepper',
  'paprika',
  'smoked paprika',
  'cumin',
  'chili powder',
  'curry powder',
  'garam masala',
  'oregano',
  'thyme',
  'rosemary',
  'cinnamon',
  'red pepper flakes',
  'taco seasoning',
  'bay leaves',
  // Misc
  'peanuts',
  'cashews',
  'sesame seeds',
  'dijon mustard',
  'ketchup',
  'mayonnaise',
  'frozen peas',
  'edamame',
];
