/**
 * M5.8 review table: for every pantry name a household is offered (the
 * `COMMON_PANTRY` list and the autocomplete `INGREDIENT_DICTIONARY`) against
 * every non-staple ingredient name in the curated library, which decisions
 * the shared matcher (`covers` in src/engine/pantryMatch.ts) changed versus
 * the old two-way substring rule the shopping list used.
 *
 *   npx tsx --tsconfig ./tsconfig.json scripts/pantryMatchTable.ts > PANTRY-MATCH-REVIEW.md
 *
 * "Still covered" = kept off the list before and after. "Now on the list" =
 * the old rule dropped it, the new rule doesn't. "Newly covered" = the old
 * rule put it on the list, the new rule treats it as on hand.
 */
import { RECIPES } from '@/data/seed/recipes';
import { COMMON_PANTRY, INGREDIENT_DICTIONARY } from '@/domain/constants';
import { covers } from '@/engine/pantryMatch';

const lower = (s: string) => s.trim().toLowerCase();
const oldRule = (pantry: string, name: string) => {
  const p = lower(pantry);
  const n = lower(name);
  return n.includes(p) || p.includes(n);
};

const names = [
  ...new Set(RECIPES.filter((r) => !r.sourceName).flatMap((r) => r.ingredients.filter((i) => !i.pantryStaple).map((i) => lower(i.name)))),
].sort();

function table(title: string, pantryNames: string[], changedOnly: boolean): string[] {
  const out = [`## ${title}`, '', '| Pantry item | Still covered | Now on the list | Newly covered |', '|---|---|---|---|'];
  let still = 0;
  let nowOnList = 0;
  let newly = 0;
  for (const p of pantryNames) {
    const s = names.filter((n) => oldRule(p, n) && covers(p, n));
    const l = names.filter((n) => oldRule(p, n) && !covers(p, n));
    const g = names.filter((n) => !oldRule(p, n) && covers(p, n));
    still += s.length;
    nowOnList += l.length;
    newly += g.length;
    if (changedOnly && l.length === 0 && g.length === 0) continue;
    const cell = (xs: string[]) => xs.join(', ') || '—';
    out.push(`| ${p} | ${cell(s)} | ${cell(l)} | ${cell(g)} |`);
  }
  out.splice(2, 0, `${pantryNames.length} pantry names × ${names.length} curated ingredient names: **${still}** still covered, **${nowOnList}** now on the list, **${newly}** newly covered.`, '');
  return out;
}

const lines = [
  '# Pantry matching — old vs new decisions (M5.8)',
  '',
  'Generated by `scripts/pantryMatchTable.ts`. Pairs neither rule matches are omitted.',
  '',
  ...table('COMMON_PANTRY (every name)', COMMON_PANTRY, false),
  '',
  ...table('Autocomplete dictionary (only names whose decisions changed)', [...new Set(INGREDIENT_DICTIONARY.map(lower))], true),
  '',
];
console.log(lines.join('\n'));
