/**
 * Content-quality gate for the hand-curated recipe library (M2.2b) and the
 * hand-curated sides/sauces library (M4.2). Run with:
 *
 *   npx tsx --tsconfig ./tsconfig.json scripts/validateRecipes.ts
 *
 * Content-quality and allergen-coverage checks (steps, descriptions,
 * ingredient-mention, keyword-vs-declared-allergen) run on all hand-authored
 * recipes — curated mains (id NOT starting with `mealdb-`) and
 * `recipeSides.ts` — held to the same standard. Imported recipes are out of
 * scope for that part; their source text is their fidelity anchor, and their
 * allergens field is already generated by the same keyword rules (P1-1).
 * The canonical-allergen-label check (P1-1) runs on every recipe, curated,
 * side, and imported, since a mis-spelled label like 'TreeNuts' is dangerous
 * wherever it appears. Fails loudly (non-zero exit) listing every offending
 * recipe id, rather than stopping at the first problem, so a whole batch's
 * gaps show up in one run.
 *
 * This intentionally stays a standalone script rather than a jest test
 * (M2.5 added `npm test` for the engine folder): it's a one-shot content/data
 * gate over the static seed library, not a unit test over varied inputs.
 */
import { Recipe } from '@/domain/models';
import { RECIPES } from '@/data/seed/recipes';
import { recipeSides } from '@/data/seed/recipeSides';
import { COMMON_ALLERGENS } from '@/domain/constants/options';
import { inferAllergens, unsupportedProvides } from '@/data/import/normalize';

const MIN_STEPS = 5;
const MIN_STEP_CHARS = 40;
const OVEN_TECHNIQUES = ['roast', 'bake', 'broil'];
const OVEN_TEMP_PATTERN = /\d{3}\s*°?\s*F\b/i;

// Descriptive modifiers that legitimately won't appear in a step's prose
// the way they appear in an ingredient list (e.g. steps say "the chicken",
// not "the boneless skinless chicken breasts"). Excluded when picking the
// "significant" word(s) an ingredient must be referenced by.
const MODIFIER_STOPWORDS = new Set([
  'fresh', 'baby', 'large', 'small', 'medium', 'extra', 'virgin', 'whole',
  'ripe', 'canned', 'dried', 'frozen', 'shredded', 'grated', 'sliced',
  'halved', 'peeled', 'cooked', 'raw', 'cold', 'warm', 'room', 'plain',
  'unflavored', 'packed', 'drained', 'rinsed', 'softened', 'melted',
  'boneless', 'skinless', 'unsalted', 'low', 'sodium', 'reduced', 'light',
  'organic', 'chopped', 'diced', 'minced', 'crushed', 'ground', 'thin',
  'thick', 'coarse', 'temperature',
]);

const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9\s]/g, ' ');

/** Significant (distinguishing) words from an ingredient name — the parts a
 * step would plausibly actually say, e.g. "spinach" from "baby spinach". */
function significantWords(ingredientName: string): string[] {
  const words = norm(ingredientName)
    .split(/\s+/)
    .filter((w) => w.length >= 3 && !MODIFIER_STOPWORDS.has(w));
  return words.length > 0 ? words : norm(ingredientName).split(/\s+/).filter(Boolean);
}

interface Violation {
  recipeId: string;
  message: string;
}

function validateRecipe(recipe: Recipe, violations: Violation[]) {
  const fail = (message: string) => violations.push({ recipeId: recipe.id, message });

  if (recipe.steps.length < MIN_STEPS) {
    fail(`only ${recipe.steps.length} step(s) (need >= ${MIN_STEPS})`);
  }

  recipe.steps.forEach((step, i) => {
    if (step.length < MIN_STEP_CHARS) {
      fail(`step ${i + 1} too short (${step.length} chars, need >= ${MIN_STEP_CHARS}): "${step}"`);
    }
  });

  const stepText = norm(recipe.steps.join(' '));
  for (const ing of recipe.ingredients) {
    if (ing.pantryStaple) continue;
    const words = significantWords(ing.name);
    // Tolerate simple plural/singular mismatches ("limes" in the ingredient
    // list vs "lime" in a step, or "tomato" vs "tomatoes") rather than
    // demanding the exact same inflection.
    const referenced = words.some((w) => {
      const forms = new Set([w, w.replace(/ies$/, 'y'), w.replace(/es$/, ''), w.replace(/s$/, '')]);
      return Array.from(forms).some((f) => f.length >= 3 && new RegExp(`\\b${f}`).test(stepText));
    });
    if (!referenced) {
      fail(`ingredient "${ing.name}" is not referenced in any step`);
    }
  }

  const usesOven = recipe.techniques.some((t) => OVEN_TECHNIQUES.includes(t.toLowerCase()));
  if (usesOven && !recipe.steps.some((s) => OVEN_TEMP_PATTERN.test(s))) {
    fail(`uses ${recipe.techniques.filter((t) => OVEN_TECHNIQUES.includes(t.toLowerCase())).join('/')} but no step states an oven temperature`);
  }

  if (!recipe.description || recipe.description.trim().length === 0) {
    fail('missing description');
  }
}

const CANONICAL_ALLERGENS = new Set(COMMON_ALLERGENS);

/** Every recipe's allergens must use the exact canonical spelling from
 * options.ts — this is the check that would have caught 'TreeNuts' vs
 * 'Tree Nuts' (P0-1). Runs over all recipes, curated and imported, since a
 * future normalize.ts regression could reintroduce a bad label either way. */
function validateAllergenLabels(recipe: Recipe, violations: Violation[]) {
  for (const a of recipe.allergens) {
    if (!CANONICAL_ALLERGENS.has(a)) {
      violations.push({
        recipeId: recipe.id,
        message: `allergen "${a}" is not a canonical label (expected one of: ${COMMON_ALLERGENS.join(', ')})`,
      });
    }
  }
}

/** Curated recipes only: if the ingredient list contains a nut/peanut/
 * shellfish/fish/egg/dairy/soy/gluten/sesame keyword, the matching allergen
 * must be declared. Reuses normalize.ts's inferAllergens so the keyword
 * rules stay in one place. Imported recipes are skipped here — their
 * allergens field IS inferAllergens's output already, so re-running it would
 * only prove the generator agrees with itself. */
function validateAllergenCoverage(recipe: Recipe, violations: Violation[]) {
  const ingText = ' ' + recipe.ingredients.map((i) => i.name).join(' ') + ' ';
  const expected = inferAllergens(ingText.toLowerCase());
  const declared = new Set(recipe.allergens.map((a) => a.toLowerCase()));
  for (const allergen of expected) {
    if (!declared.has(allergen.toLowerCase())) {
      violations.push({
        recipeId: recipe.id,
        message: `ingredients suggest allergen "${allergen}" but it is not declared (declared: [${recipe.allergens.join(', ')}])`,
      });
    }
  }
}

/** Curated mains that are honestly protein-light — reviewed by hand (M4.2
 * part 1) and left as `role: 'main'` with `provides` that truthfully omits
 * 'protein', rather than inventing a protein that isn't there
 * (ADVISOR-HANDOFF #21: no content-rewrite project). This list is frozen: a
 * *new* protein-less curated main fails the gate below until someone
 * deliberately adds its id here, so a real content gap can't slip in
 * silently. Every one of these gets a genuine protein-capable side
 * (recipeSides.ts) to optionally pair with once composition (M4.2 part 2)
 * exists. */
const PROTEIN_LESS_MAIN_ALLOWLIST = new Set([
  'fr-ratatouille',
  'in-aloo-gobi',
  'cn-veg-lo-mein',
  'in-veg-biryani',
  'jp-yaki-udon',
  'gr-briam',
  'fr-potato-leek-soup',
]);

/** Curated mains only (role is absent/'main' for all of them today): every
 * one must declare `provides`, and must include 'protein' in it unless it's
 * on the frozen allowlist above. */
function validateMainProvides(recipe: Recipe, violations: Violation[]) {
  if (recipe.role && recipe.role !== 'main') return;
  if (!recipe.provides || recipe.provides.length === 0) {
    violations.push({ recipeId: recipe.id, message: 'curated main is missing `provides`' });
    return;
  }
  if (!recipe.provides.includes('protein') && !PROTEIN_LESS_MAIN_ALLOWLIST.has(recipe.id)) {
    violations.push({
      recipeId: recipe.id,
      message:
        'curated main declares `provides` without \'protein\' and is not on the frozen protein-less allowlist — ' +
        'add it to PROTEIN_LESS_MAIN_ALLOWLIST in this script if that is a deliberate, reviewed choice',
    });
  }
}

/** Hard gate (M4.2): a declared `provides` entry must be backed by a real
 * ingredient — reuses the exact same inference normalize.ts uses for
 * imported recipes, so hand-authored and generated `provides` are held to
 * one standard. Deliberately asymmetric: this never requires declaring
 * every vegetable/starch/protein a dish happens to contain, only that
 * whatever IS declared is true. Recreating "must declare every vegetable"
 * would recreate the hard gate the product owner explicitly rejected
 * (ADVISOR-HANDOFF #21 — a vegetable is a preference, not a gate). */
function validateProvidesPlausibility(recipe: Recipe, violations: Violation[]) {
  const unsupported = unsupportedProvides(
    recipe.provides,
    recipe.primaryProtein,
    recipe.ingredients.map((i) => i.name),
  );
  for (const p of unsupported) {
    violations.push({
      recipeId: recipe.id,
      message: `declares provides "${p}" but no ingredient supports it (declared: [${recipe.provides!.join(', ')}])`,
    });
  }
}

const curated = RECIPES.filter((r) => !r.id.startsWith('mealdb-'));
const handAuthored = [...curated, ...recipeSides];
const allRecipes = [...RECIPES, ...recipeSides];
console.log(
  `Validating ${curated.length} curated recipes + ${recipeSides.length} sides/sauces ` +
    `(plus allergen labels and provides plausibility on all ${allRecipes.length} recipes)...\n`,
);

const violations: Violation[] = [];
for (const recipe of handAuthored) {
  validateRecipe(recipe, violations);
  validateAllergenCoverage(recipe, violations);
}
for (const recipe of curated) validateMainProvides(recipe, violations);
for (const recipe of allRecipes) {
  validateAllergenLabels(recipe, violations);
  validateProvidesPlausibility(recipe, violations);
}

const failedIds = Array.from(new Set(violations.map((v) => v.recipeId)));

if (violations.length === 0) {
  console.log(
    `All ${curated.length} curated recipes + ${recipeSides.length} sides/sauces pass, and all ` +
      `${allRecipes.length} recipes use canonical allergen labels with plausible \`provides\`. ✅`,
  );
  process.exit(0);
}

for (const id of failedIds) {
  console.log(`FAIL - ${id}`);
  for (const v of violations.filter((x) => x.recipeId === id)) {
    console.log(`  - ${v.message}`);
  }
}

console.log(
  `\n${allRecipes.length} recipes checked (${curated.length} curated + ${recipeSides.length} sides/sauces), ` +
    `${failedIds.length} recipe(s) failed (${violations.length} total violations).`,
);
process.exit(1);
